=== nullkru/code/python/pm/daten/APL_MAP.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 rel. 3 U (http://www.altova.com) by Rainer Blickle (Siemens AG, Logistics and Assembly Systems) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.post.ch/ids/apl" targetNamespace="http://www.post.ch/ids/apl" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="APL_MAP">
		<xs:annotation>
			<xs:documentation>Analysis and Planning sends information for each of 9 centers.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="BZ" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>The BZ where the xml data is assigned to</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="PLZ" type="xs:int">
								<xs:annotation>
									<xs:documentation>The 6-digit-postcode of the BZ.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="Transport" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="ArrivalTime" type="xs:dateTime"/>
										<xs:element name="ID" type="xs:string">
											<xs:annotation>
												<xs:documentation>The human-readable Name for this Transport</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="Amount" maxOccurs="unbounded">
											<xs:annotation>
												<xs:documentation>"Verarbeitungs Produkt" defines product, handling, and speed for the mail.</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:all>
													<xs:element name="Vap">
														<xs:annotation>
															<xs:documentation>the first 3 digits of the BB lable</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:length value="3"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="Count" type="xs:int">
														<xs:annotation>
															<xs:documentation>Amount of the VAP for this transport. The value of the Amount is in items.</xs:documentation>
														</xs:annotation>
													</xs:element>
												</xs:all>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== nullkru/code/python/pm/daten/Test_8a_28_03_2008/map_2008-04-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<APL_MAP xmlns="http://www.post.ch/ids/apl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.post.ch/ids/apl APL_MAP.xsd">
	<BZ>
		<PLZ>130050</PLZ>
		<Transport>
			<ArrivalTime>TIMESTAMP</ArrivalTime>
			<ID>Transport</ID>
		<Amount>
			<Vap>AAA</Vap>
			<Count>90</Count>
		</Amount>
		<Amount>
			<Vap>BAA</Vap>
			<Count>0</Count>
		</Amount>
		<Amount>
			<Vap>EAA</Vap>
			<Count>0</Count>
		</Amount>
		<Amount>
			<Vap>FAA</Vap>
			<Count>0</Count>
		</Amount>
		</Transport>
	</BZ>
</APL_MAP>
